apiVersion: v1
data:
  {{- if .Values.options.secretKey }}
  SECRET_KEY: {{ .Values.options.secretKey | b64enc }}
  {{ else }}
  SECRET_KEY: {{ randAlpha 8 | b64enc }}
  {{- end}}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ include "gitea.fullname" . }}-secret-key
  labels:
{{ include "gitea.labels" . | indent 4 }}
